# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-20 17:10
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='评论内容')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户评论',
                'verbose_name_plural': '用户评论',
            },
        ),
        migrations.CreateModel(
            name='UserOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.IntegerField(choices=[(0, '转发'), (1, '收藏'), (2, '感谢'), (3, '评论'), (4, '回复')], verbose_name='操作类型')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name='被操作的文章')),
            ],
            options={
                'verbose_name': '用户操作',
                'verbose_name_plural': '用户操作',
            },
        ),
    ]
