# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-20 17:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0002_article_author'),
        ('user_operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroperation',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_user', to=settings.AUTH_USER_MODEL, verbose_name='操作用户'),
        ),
        migrations.AddField(
            model_name='comments',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='article.Article', verbose_name='被评论文章'),
        ),
        migrations.AddField(
            model_name='comments',
            name='critics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critics_user', to=settings.AUTH_USER_MODEL, verbose_name='评论人'),
        ),
        migrations.AddField(
            model_name='comments',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='user_operation.Comments', verbose_name='被评论人(楼层)'),
        ),
    ]
