# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-24 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0003_auto_20181024_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='消息标题'),
        ),
    ]
