# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-25 20:46
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0004_auto_20181020_1809'),
        ('user_operation', '0004_usermessage_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(choices=[(1, '收藏'), (2, '感谢'), (3, '举报')], default=1)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('article', models.ForeignKey(help_text='文章', on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name='文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户行为',
                'verbose_name_plural': '用户行为',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userfav',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='userfav',
            name='article',
        ),
        migrations.RemoveField(
            model_name='userfav',
            name='user',
        ),
        migrations.AlterField(
            model_name='useroperation',
            name='operation_type',
            field=models.IntegerField(choices=[(0, '转发'), (1, '收藏'), (2, '感谢'), (3, '评论'), (4, '回复'), (5, '举报')], verbose_name='操作类型'),
        ),
        migrations.DeleteModel(
            name='UserFav',
        ),
        migrations.AlterUniqueTogether(
            name='useraction',
            unique_together=set([('user', 'article', 'action')]),
        ),
    ]
