# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-20 17:10
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='话题标题')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='文章内容')),
                ('article_type', models.IntegerField(choices=[(1, '讨论'), (2, '询问'), (3, '记录'), (4, '牙套'), (5, '智齿'), (6, '种植')], help_text='文章类别', verbose_name='文章类别')),
                ('click_num', models.IntegerField(default=0, verbose_name='被点击次数')),
                ('thanks_num', models.IntegerField(default=0, verbose_name='被感谢次数')),
                ('fav_num', models.IntegerField(default=0, verbose_name='被收藏次数')),
                ('forwarding_num', models.IntegerField(default=0, verbose_name='被转发次数')),
                ('comments_num', models.IntegerField(default=0, verbose_name='被评论次数')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='文章更新时间')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
