# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-20 18:09
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20181020_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='文章内容'),
        ),
    ]
